# Generated by Django 4.1 on 2022-09-02 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='officeMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(choices=[('mo1', 'magazzino@'), ('mo2', 'patrimonio@'), ('mo3', 'tecnico@'), ('mo4', 'manutenzione@'), ('mo5', 'tributi@'), ('mo6', 'ragioneria@'), ('mo7', 'informatica@'), ('mo8', '@'), ('mo9', '@'), ('mo10', '@'), ('mo11', '@'), ('mo12', '@')], max_length=100)),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='customUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('surname', models.CharField(blank=True, default='', max_length=100)),
                ('cf', models.CharField(blank=True, default='', max_length=100)),
                ('hasMail', models.BooleanField()),
                ('personalMail', models.CharField(blank=True, default='', max_length=100)),
                ('hasLAN', models.BooleanField()),
                ('LANid', models.CharField(blank=True, default='A516-', max_length=100)),
                ('hasAdweb', models.BooleanField()),
                ('hasAscot', models.BooleanField()),
                ('hasSDI', models.BooleanField()),
                ('hasIteratti', models.BooleanField()),
                ('hasBoxapps', models.BooleanField()),
                ('hasWebsite', models.BooleanField()),
                ('websiteUser', models.BooleanField()),
                ('websiteAdmin', models.BooleanField()),
                ('hasCRM', models.BooleanField()),
                ('hasAvcp', models.BooleanField()),
                ('hasFVGPay', models.BooleanField()),
                ('hasSue', models.BooleanField()),
                ('hasSercScuola', models.BooleanField()),
                ('officeMail', models.ManyToManyField(to='api.officemail')),
            ],
            options={
                'ordering': [],
            },
        ),
    ]
