# Generated by Django 4.1 on 2022-09-06 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='LANid',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hasAdweb',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hasLAN',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hasMail',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='officeMail',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='personalMail',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cf',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Codice fiscale'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cognome'),
        ),
        migrations.AlterField(
            model_name='officemail',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='userLan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanId', models.CharField(blank=True, default='A516-', max_length=100, verbose_name='Nome utente rete locale')),
                ('lanFolders', models.ManyToManyField(to='api.officemail')),
            ],
        ),
        migrations.CreateModel(
            name='userEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalMail', models.CharField(blank=True, default='', max_length=100, verbose_name='Mail personale')),
                ('officeMail', models.ManyToManyField(to='api.officemail')),
            ],
        ),
        migrations.CreateModel(
            name='userAdweb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adwebId', models.CharField(blank=True, default='A516-', max_length=100, verbose_name='Nome utente')),
                ('adwebOffices', models.ManyToManyField(to='api.officemail')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='adweb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.useradweb'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userlan'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.useremail'),
        ),
    ]
