# Generated by Django 4.1 on 2022-09-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customuser_lanid_remove_customuser_hasadweb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='officeAdweb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offices', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='officemail',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hasSercScuola',
        ),
        migrations.AddField(
            model_name='customuser',
            name='adwebOffices',
            field=models.ManyToManyField(to='api.officeadweb'),
        ),
    ]
