# Generated by Django 4.1 on 2022-09-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_officeadweb_alter_officemail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adwebDeleted',
            field=models.BooleanField(default=False, verbose_name='Adweb - Cancellato / disattivato'),
        ),
        migrations.AlterField(
            model_name='officeadweb',
            name='offices',
            field=models.CharField(blank=True, choices=[('mo1', 'magazzino@'), ('mo2', 'patrimonio@'), ('mo3', 'tecnico@'), ('mo4', 'manutenzione@'), ('mo5', 'tributi@'), ('mo6', 'ragioneria@'), ('mo7', 'informatica@'), ('mo8', '@'), ('mo9', '@'), ('mo10', '@'), ('mo11', '@'), ('mo12', '@')], default='', max_length=100),
        ),
    ]
