# Generated by Django 4.1 on 2022-09-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_adwebdeleted_alter_officeadweb_offices'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lanDeleted',
            field=models.BooleanField(default=False, verbose_name='Lan - Cancellata / disattivata'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mailDeleted',
            field=models.BooleanField(default=False, verbose_name='Mail - Cancellata / disattivata'),
        ),
        migrations.AlterField(
            model_name='officeadweb',
            name='offices',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='useradweb',
            name='adwebOffices',
            field=models.ManyToManyField(to='api.officeadweb'),
        ),
    ]
