# Generated by Django 4.1 on 2022-09-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_landeleted_customuser_maildeleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='officeSDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offices', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='alboPretDeleted',
            field=models.BooleanField(default=False, verbose_name='Albo pretorio - Cancellato / disattivato'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='crmDeleted',
            field=models.BooleanField(default=False, verbose_name='CRM - Cancellato / disattivato'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hasAlboPret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hasServScuola',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sdiDeleted',
            field=models.BooleanField(default=False, verbose_name='SDI - Cancellato / disattivato'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='servScuolaDeleted',
            field=models.BooleanField(default=False, verbose_name='Servizi scolastici - Cancellato / disattivato'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hasAscot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hasAvcp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hasBoxapps',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hasCRM',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hasFVGPay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hasIteratti',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hasSDI',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hasSue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hasWebsite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='websiteAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='websiteUser',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='userSDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdiId', models.CharField(blank=True, default='', max_length=100, verbose_name='LOGIN FVG')),
                ('sdiOffices', models.ManyToManyField(to='api.officesdi')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='sdiOffices',
            field=models.ManyToManyField(to='api.officesdi'),
        ),
    ]
