# Generated by Django 4.1 on 2022-09-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_officesdi_customuser_albopretdeleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mailOffices',
            field=models.ManyToManyField(to='api.officemail'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lan',
            field=models.CharField(default='A516-', max_length=120, verbose_name='ID personale'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mail',
            field=models.CharField(default='@comune.aviano.pn.it', max_length=120, verbose_name='Mail personale'),
        ),
    ]
