# Generated by Django 4.1 on 2022-09-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_mailoffices_alter_customuser_lan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='adweb',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='adwebOffices',
        ),
        migrations.AddField(
            model_name='customuser',
            name='adwebOffice',
            field=models.CharField(choices=[('ao0', '--'), ('ao1', 'Servizi alla persona e alla comunità'), ('ao2', 'Servizi demografici'), ('ao3', 'Servizi educativi e culturali'), ('ao4', 'Servizio affari generali urp protocollo'), ('ao5', 'Servizio appalti e contratti'), ('ao6', 'Servizio turismo sport e associazioni'), ('ao7', 'Servizio casa di soggiorno anziani'), ('ao8', 'Servizi informatici'), ('ao9', 'Servizio contabilità e bilancio'), ('ao10', 'Servizio tributi'), ('ao11', 'Servizio ambiente ed energie rinnovabili'), ('ao12', 'Servizio SUAP e commercio'), ('ao13', 'Servizio urbanistica ed edilizia privata'), ('ao14', 'Servizio gestione rifiuti'), ('ao15', 'Servizio lavori pubblici ed espropri'), ('ao16', 'Servizio manutenzione'), ('ao17', 'Servizio patrimonio'), ('ao18', 'Servizio Polizia locale'), ('ao19', 'Servizio Segreteria particolare e rappresentanza'), ('ao20', 'Segretario generale'), ('ao21', 'Ufficio gestione delle risorse umane - MCM')], default='ao1', max_length=4),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lanRole',
            field=models.CharField(choices=[('l1', 'Utente'), ('l2', 'Amministratore')], default='l1', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='websiteRole',
            field=models.CharField(choices=[('w1', 'Utente'), ('w2', 'Amministratore')], default='w1', max_length=2),
        ),
    ]
