# Generated by Django 4.1 on 2022-09-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_customuser_adweb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradweb',
            name='adwebOffices',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='websiteAdmin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='websiteUser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='boxAppsRole',
            field=models.CharField(choices=[('b1', 'Utente'), ('b2', 'Amministratore')], default='b1', max_length=4),
        ),
        migrations.AddField(
            model_name='customuser',
            name='crmRole',
            field=models.CharField(choices=[('c1', 'Utente'), ('c2', 'Amministratore')], default='c1', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lanDeleted',
            field=models.BooleanField(default=False, verbose_name='Lan disattivata'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lanRole',
            field=models.CharField(choices=[('l1', 'Utente'), ('l2', 'Amministratore')], default='l1', max_length=2, verbose_name='Ruolo in LAN'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mailDeleted',
            field=models.BooleanField(default=False, verbose_name='Mail disattivata'),
        ),
        migrations.DeleteModel(
            name='officeAdweb',
        ),
        migrations.DeleteModel(
            name='userAdweb',
        ),
    ]
