# Generated by Django 4.1 on 2022-09-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_useradweb_adweboffices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='office',
            field=models.CharField(choices=[('o0', '--'), ('o1', 'Informatica'), ('o2', 'Ragioneria'), ('o3', 'Tributi'), ('o4', 'Segreteria'), ('o5', 'Urp'), ('o6', 'Protocollo'), ('o7', 'Messo'), ('o8', 'Polizia locale'), ('o9', 'Anagrafe'), ('o10', 'Magazzino'), ('o11', 'LLPP'), ('o12', 'Ambiente'), ('o13', 'Commercio'), ('o14', 'Edilizia'), ('o15', 'Biblioteca'), ('o16', 'Informagiovani'), ('o17', 'CDR')], default='b1', max_length=4),
        ),
    ]
