MAIN_OFFICE_CHOICES = [
  ('o0', '--'),
  ('o1', 'Informatica'),
  ('o2', 'Ragioneria'),
  ('o3', 'Tributi'),
  ('o4', 'Segreteria'),
  ('o5', 'Urp'),
  ('o6', 'Protocollo'),
  ('o7', 'Messo'),
  ('o8', 'Polizia locale'),
  ('o9', 'Anagrafe'),
  ('o10', 'Magazzino'),
  ('o11', 'LLPP'),
  ('o12', 'Ambiente'),
  ('o13', 'Commercio'),
  ('o14', 'Edilizia'),
  ('o15', 'Biblioteca'),
  ('o16', 'Informagiovani'),
  ('o17', 'CDR'),
]
LAN_OFFICE_CHOICES = [
  ('l0', '--'),
  ('l1', 'Affari Generali'),
  ('l2', 'Ambiente'),
  ('l3', 'Anagrafe'),
  ('l4', 'Associazioni'),
  ('l5', 'Biblioteca'),
  ('l6', 'Casa di riposo'),
  ('l7', 'Commercio'),
  ('l8', 'Contratti'),
  ('l9', 'Informagiovani'),
  ('l10', 'Lavori pubblici'),
  ('l11', 'Manutenzione'),
  ('l12', 'Patrimonio'),
  ('l13', 'Personale'),
  ('l14', 'Polizia municipale'),
  ('l15', 'Protocollo'),
  ('l16', 'Ragioneria'),
  ('l17', 'Segreteria'),
  ('l18', 'Segreteria sindaco'),
  ('l19', 'Servizi educativi'),
  ('l20', 'Sistemi informatici'),
  ('l21', 'Tributi'),
  ('l22', 'Urbanistica'),
]
MAIL_OFFICE_CHOICES = [
  ('mo0', '--'),
  ('mo1', 'magazzino@'),
  ('mo2', 'patrimonio@'),
  ('mo3', 'tecnico@'),
  ('mo4', 'manutenzione@'),
  ('mo5', 'tributi@'),
  ('mo6', 'ragioneria@'),
  ('mo7', 'informatica@'),
  ('mo8', '@'),
  ('mo9', '@'),
  ('mo10', '@'),
  ('mo11', '@'),
  ('mo12', '@'),
]
ADWEB_OFFICE_CHOICES = [
  ('ao0', '--'),
  ('ao1', 'Servizi alla persona e alla comunità'),
  ('ao2', 'Servizi demografici'),
  ('ao3', 'Servizi educativi e culturali'),
  ('ao4', 'Servizio affari generali urp protocollo'),
  ('ao5', 'Servizio appalti e contratti'),
  ('ao6', 'Servizio turismo sport e associazioni'),
  ('ao7', 'Servizio casa di soggiorno anziani'),
  ('ao8', 'Servizi informatici'),
  ('ao9', 'Servizio contabilità e bilancio'),
  ('ao10', 'Servizio tributi'),
  ('ao11', 'Servizio ambiente ed energie rinnovabili'),
  ('ao12', 'Servizio SUAP e commercio'),
  ('ao13', 'Servizio urbanistica ed edilizia privata'),
  ('ao14', 'Servizio gestione rifiuti'),
  ('ao15', 'Servizio lavori pubblici ed espropri'),
  ('ao16', 'Servizio manutenzione'),
  ('ao17', 'Servizio patrimonio'),
  ('ao18', 'Servizio Polizia locale'),
  ('ao19', 'Servizio Segreteria particolare e rappresentanza'),
  ('ao20', 'Segretario generale'),
  ('ao21', 'Ufficio gestione delle risorse umane - MCM'),
]
ITERATTI_OFFICE_CHOICES = [
  ('i0', '--'),
  ('i1', 'Generale'),
  ('i2', 'Affari generali'),
  ('i3', ''),
  ('i4', ''),
  ('i5', ''),
  ('i6', ''),
  ('i7', ''),
  ('i8', 'Informatica'),
  ('i9', 'Ragioneria'),
  ('i10', 'Tributi'),
  ('i11', ''),
  ('i12', ''),
  ('i13', ''),
  ('i14', ''),
  ('i15', ''),
  ('i16', ''),
  ('i17', ''),
  ('i18', ''),
  ('i19', ''),
  ('i20', ''),
  ('i21', ''),
]
LAN_ROLES_CHOICES = [
  ('l1', 'Utente'),
  ('l2', 'Amministratore'),
]

WEBSITE_ROLES_CHOICES = [
  ('w0', '--'),
  ('w1', 'Utente'),
  ('w2', 'Amministratore'),
]

BOXAPP_ROLES_CHOICES = [
  ('b0', '--'),
  ('b1', 'Utente'),
  ('b2', 'Amministratore'),
]

SERVSCOL_ROLES_CHOICES = [
  ('ss0', '--'),
  ('ss1', 'Utente'),
  ('ss2', 'Amministratore'),
]

CRM_ROLES_CHOICES = [
  ('c0', '--'),
  ('c1', 'Utente'),
  ('c2', 'Amministratore'),
]