MAIN_OFFICE_CHOICES = [
  ('o0', '--'),
  ('o1', 'Informatica'),
  ('o2', 'Ragioneria'),
  ('o3', 'Tributi'),
  ('o4', 'Segreteria'),
  ('o5', 'Urp'),
  ('o6', 'Protocollo'),
  ('o7', 'Messo'),
  ('o8', 'Polizia locale'),
  ('o9', 'Anagrafe'),
  ('o10', 'Magazzino'),
  ('o11', 'LLPP'),
  ('o12', 'Ambiente'),
  ('o13', 'Commercio'),
  ('o14', 'Edilizia'),
  ('o15', 'Biblioteca'),
  ('o16', 'Informagiovani'),
  ('o17', 'CDR'),
  ('o18', 'Politico')
]
LAN_OFFICE_CHOICES = [
  ('l0', '--'),
  ('l1', 'Affari Generali'),
  ('l2', 'Ambiente'),
  ('l3', 'Anagrafe'),
  ('l4', 'Associazioni'),
  ('l5', 'Biblioteca'),
  ('l6', 'Casa di riposo'),
  ('l7', 'Commercio'),
  ('l8', 'Contratti'),
  ('l9', 'Informagiovani'),
  ('l10', 'Lavori pubblici'),
  ('l11', 'Manutenzione'),
  ('l12', 'Patrimonio'),
  ('l13', 'Personale'),
  ('l14', 'Polizia municipale'),
  ('l15', 'Protocollo'),
  ('l16', 'Ragioneria'),
  ('l17', 'Segreteria'),
  ('l18', 'Segreteria sindaco'),
  ('l19', 'Servizi educativi'),
  ('l20', 'Sistemi informatici'),
  ('l21', 'Tributi'),
  ('l22', 'Urbanistica'),
]
MAIL_OFFICE_CHOICES = [
  ('mo0', '--'),
  ('mo1', 'magazzino@'),
  ('mo2', 'patrimonio@'),
  ('mo3', 'tecnico@'),
  ('mo4', 'manutenzione@'),
  ('mo5', 'tributi@'),
  ('mo6', 'ragioneria@'),
  ('mo7', 'informatica@'),
  ('mo8', 'segreteria@'),
  ('mo9', 'sindaco@'),
  ('mo10', 'polizia.locale@'),
  ('mo11', 'serviziscolastici@'),
  ('mo12', '@'),
  ('mo13', '@'),
  ('mo14', '@'),
  ('mo15', '@'),
  ('mo16', '@'),
  ('mo17', '@'),
  ('mo18', '@'),
  ('mo19', '@'),
  ('mo20', 'vicesindaco@'),
]
ADWEB_OFFICE_CHOICES = [
  ('ao0', '--'),
  ('ao1', 'Servizi alla persona e alla comunità'),
  ('ao2', 'Servizi demografici'),
  ('ao3', 'Servizi educativi e culturali'),
  ('ao4', 'Servizio affari generali urp protocollo'),
  ('ao5', 'Servizio appalti e contratti'),
  ('ao6', 'Servizio turismo sport e associazioni'),
  ('ao7', 'Servizio casa di soggiorno anziani'),
  ('ao8', 'Servizi informatici'),
  ('ao9', 'Servizio contabilità e bilancio'),
  ('ao10', 'Servizio tributi'),
  ('ao11', 'Servizio ambiente ed energie rinnovabili'),
  ('ao12', 'Servizio SUAP e commercio'),
  ('ao13', 'Servizio urbanistica ed edilizia privata'),
  ('ao14', 'Servizio gestione rifiuti'),
  ('ao15', 'Servizio lavori pubblici ed espropri'),
  ('ao16', 'Servizio manutenzione'),
  ('ao17', 'Servizio patrimonio'),
  ('ao18', 'Servizio Polizia locale'),
  ('ao19', 'Servizio Segreteria particolare e rappresentanza'),
  ('ao20', 'Segretario generale'),
  ('ao21', 'Ufficio gestione delle risorse umane - MCM'),
  ('ao22', 'Nominativo per consigli e giunte')
]
ITERATTI_OFFICE_CHOICES = [
  ('i0', '--'),
  ('i1', 'AAGG - AFFARI GENERALI'),
  ('i2', 'AANA - AREA ANAGRAFE'),
  ('i3', 'ACA	 - AREA CONTRATTI E ASSICURAZIONI'),
  ('i4', 'AEF	 - AREA ECONOMICO FINANZIARIA'),
  ('i5', 'ALPP - AREA LAVORI PUBBLICI E PATRIMONIO'),
  ('i6', 'AMA	 - AREA MESSI E ALBO'),
  ('i7', 'AMB  - UFFICIO ECOLOGIA-AMBIENTE C/O UFFICIO URBANISTICA - SEDE'),
  ('i8', 'AN   - UFFICIO ANAGRAFE - STATO CIVILE - LEVA - ELETTORALE - ANAGRAFE CANINA - SEDE'),
  ('i9', 'AUAP - AREA URBANISTICA E ATTIVITÀ PRODUTTIVE'),
  ('i10', 'BASS	- BASSO DANIELE - ASSESSORE'),
  ('i11', 'BIBLIO	- BIBLIOTECA COMUNALE - SEDE'),
  ('i12', 'CR   - CASA DI SOGGIORNO PER ANZIANI -- AVIANO'),
  ('i13', 'CREM	- CREMON MARTINA - ASSESSORE'),
  ('i14', 'GEN  - COMUNE DI AVIANO - COMUNE DI AVIANO'),
  ('i15', 'GEN_FATT - UFFICIO PROTOCOLLAZIONE FATTURE'),
  ('i16', 'GROLLO - RESPONSABILE SERVIZI SOCIO EDUCATIVI'),
  ('i17', 'INF  - UFFICIO INFORMATICO'),
  ('i18', 'MAN  - UFFICIO MANUTENZIONE - MAGAZZINO - SEDE'),
  ('i19', 'MEN  - MENEGOZ ANDREA - ASSESSORE'),
  ('i20', 'MUN  - MUNGO GIORGIA - A SSESSORE'),
  ('i21', 'PG   -	PROGETTO GIOVANI - SEDE'),
  ('i22', 'RAG  -	UFFICIO RAGIONERIA'),
  ('i23', 'RAGZ - RAGOZZINO GIUSEPPE - ASSESSORE'),
  ('i24', 'SGTAC - SETTORE GESTIONE TERRITORIO, AMBIENTE E COMMERCIO'),
  ('i25', 'SIND - SINDACO'),
  ('i26', "SUAP - SPORTELLO UNICO PER LE ATTIVITA' PRODUTTIVE E UFFICIO ATTIVITA' PRODUTTIVE COMMERCIO E LICENZE - SEDE"),
  ('i27', "SUE  - SPORTELLO UNICO PER L'EDILIZIA"),
  ('i28', 'TEST	- UFFICIO TEST ITERATTI'),
  ('i29', 'TRIB	- TRIBUTI'),
  ('i30', 'UFCOM - UFFICIO COMMERCIO E LICENZE - SEDE'),
  ('i31', 'URB  -	UFFICIO URBANISTICA - EDILIZIA PRIVATA - SEDE'),
  ('i32', 'VIG  - POLIZIA LOCALE'),
  ('i33', 'WS_EAPPALTI_UFF - UFFICIO WS EAPPALTI'),
  ('i34', 'WS_SCUOLA_UFF - UFFICIO WEB SERVICE SCUOLA'),
  ('i35', 'WS_SUE_UFF - UFFICIO PER UTENTE WEB SERVICE SUE'),
]
SDI_OFFICE_CHOICES = [
  ('sdi0', '--'),
  ('sdi1', 'Casa di soggiorno anziani'),
  ('sdi2', 'Affari generali, URP, protocollo'),
  ('sdi3', 'Segreteria generale'),
  ('sdi4', 'Gestione risorse umane'),
  ('sdi5', 'Polizia locale'),
  ('sdi6', 'Servizio contabilità'),
  ('sdi7', 'Servizio contratti'),
  ('sdi8', 'Servizio cultura biblioteca'),
  ('sdi9', 'Servizio manutenzione'),
  ('sdi10', 'Servizio personale'),
  ('sdi11', 'Servizio tributi'),
  ('sdi12', 'Settore urbanistica, ambiente, commercio'),
]
ASCOT_OFFICE_CHOICES = [
  ('a0', '--'),
  ('a1', 'Servizi alla persona e alla comunità'),
  ('a2', 'Servizi demografici'),
  ('a3', 'Servizi educativi e culturali'),
  ('a4', 'Servizio affari generali urp protocollo'),
  ('a5', 'Servizio appalti e contratti'),
  ('a6', 'Servizio turismo sport e associazioni'),
  ('a7', 'Servizio casa di soggiorno anziani'),
  ('a8', 'Servizi informatici'),
  ('a9', 'Servizio contabilità e bilancio'),
  ('a10', 'Servizio tributi'),
  ('a11', 'Servizio ambiente ed energie rinnovabili'),
  ('a12', 'Servizio SUAP e commercio'),
  ('a13', 'Servizio urbanistica ed edilizia privata'),
  ('a14', 'Servizio gestione rifiuti'),
  ('a15', 'Servizio lavori pubblici ed espropri'),
  ('a16', 'Servizio manutenzione'),
  ('a17', 'Servizio patrimonio'),
  ('a18', 'Servizio Polizia locale'),
  ('a19', 'Servizio Segreteria particolare e rappresentanza'),
  ('a20', 'Segretario generale'),
  ('a21', 'Ufficio gestione delle risorse umane - MCM'),
]

LAN_ROLES_CHOICES = [
  ('l0', '--'),
  ('l1', 'Utente'),
  ('l2', 'Amministratore'),
]
WEBSITE_ROLES_CHOICES = [
  ('w0', '--'),
  ('w1', 'Editor'),
  ('w2', 'Amministratore'),
  ('w3', 'Utente area privata'),
]
BOXAPP_ROLES_CHOICES = [
  ('b0', '--'),
  ('b1', 'Utente'),
  ('b2', 'Amministratore'),
]
SERVSCOL_ROLES_CHOICES = [
  ('ss0', '--'),
  ('ss1', 'Utente'),
  ('ss2', 'Amministratore'),
]
CRM_ROLES_CHOICES = [
  ('c0', '--'),
  ('c1', 'Utente'),
  ('c2', 'Amministratore'),
]
SUE_ROLES_CHOICES = [
  ('s0', '--'),
  ('s1', 'Utente'),
  ('s2', 'Amministratore'),
]
SUAP_ROLES_CHOICES = [
  ('s0', '--'),
  ('s1', 'Utente'),
  ('s2', 'Amministratore'),
]
AVCP_ROLES_CHOICES = [
  ('a0', '--'),
  ('a1', 'Utente'),
  ('a2', 'Amministratore'),
]
FVGPAY_ROLES_CHOICES = [
  ('f0', '--'),
  ('f1', 'Utente'),
  ('f2', 'Amministratore'),
]
ALBOPRET_ROLES_CHOICES = [
  ('ap0', '--'),
  ('ap1', 'Visualizzatore'),
  ('ap2', 'Editor'),
  ('ap3', 'Amministratore'),
]
ADWEB_ROLES_CHOICES = [
  ('a0', 'Utente'),
  ('a1', 'Addetto segreteria'),
  ('a2', 'Istruttore ragioneria'),
  ('a3', 'Potere di firma'),
  ('a5', 'Politico'),
]
ITERATTI_ROLES_CHOICES = [
  ('i0', '--'),
  ('i1', 'Utente'),
  ('i2', 'Amministratore'),
]
SDI_ROLES_CHOICES = [
  ('sdi0', '--'),
  ('sdi1', 'Utente'),
  ('sdi2', 'Amministratore'),
]
ASCOT_ROLES_CHOICES = [
  ('a0', '--'),
  ('a1', 'Utente'),
  ('a2', 'Amministratore'),
]
